import { Scale } from 'lucide-react';

const Appeals = () => {
  return (
    <div className="page-container">
      <div className="professional-header">
        <div className="professional-header-content">
          <div className="professional-title-container">
            <div className="professional-title-icon">
              <Scale size={24} />
            </div>
            <div className="professional-title-text">
              <h1 className="professional-main-title">Appeals</h1>
              <div className="professional-title-divider"></div>
            </div>
          </div>
        </div>
      </div>

      <div className="page-content">
        {/* When Can Taxpayers Appeal Section */}
        <section className="content-section">
          <h2>When can taxpayers appeal?</h2>
          <p className="content-paragraph">
            Taxpayers may appeal to RRA against decisions within 30 days following the conclusion of audits and/or receiving any assessment notices of taxes or penalties. However, disputes related to a notice of assessment generated by electronic tax system based on declaration made by a taxpayer may be administratively resolved without recourse to appeal procedure.
          </p>
        </section>

        {/* Payment During Appeals Section */}
        <section className="content-section">
          <h2>Do taxes and fines still have to be paid when appealing?</h2>
          <p className="content-paragraph">
            It is important to note that taxpayers are still required to pay any taxes or penalties within the original deadlines. Failure to do so will result in penalties and interest applying as normal. If the appeals are successful, taxpayers will receive refunds or credit notes. However, when the taxpayer has paid the undisputed portion of the tax, the Commissioner General suspends the collection of tax that is subject of appeal.
          </p>
        </section>

        {/* Appeal Process Section */}
        <section className="content-section">
          <h2>What is the process, timeframe and level of appeal?</h2>
          <p className="content-paragraph">
            In order to appeal, taxpayers must write a letter addressed to the Commissioner General of RRA within 30 days of receiving notice of the decision they wish to appeal. This letter should:
          </p>
          <ul className="content-list">
            <li>Identify the taxpayer's name and TIN.</li>
            <li>Identify the tax period and tax type(s) concerned.</li>
            <li>State the decision that is being appealed.</li>
            <li>State the reason(s) for the appeal.</li>
            <li>Contain all supporting documents, proofs and legal arguments against the assessment.</li>
            <li>Be signed by the taxpayer or legal representative.</li>
          </ul>
          <p className="content-paragraph">
            RRA is required to respond to the appeal of the taxpayer within 30 days. During this period, RRA will then either accept the appeal, invite the taxpayer to come to RRA offices to further explain the reasons for their appeal or may extend an addition of 30 days and inform the taxpayer. If the taxpayer is not satisfied with the result of the appeal, s/he may apply to RRA to reach an 'amicable agreement' or file the case to the competent court within 30 days.
          </p>
        </section>

        {/* Appeal Cost Section */}
        <section className="content-section">
          <h2>What is the cost of appeal?</h2>
          <p className="content-paragraph">
            There is no cost of appealing to RRA. However, there may be fees incurred when appealing to the Courts.
          </p>
        </section>

        {/* Supporting Documents Section */}
        <section className="content-section">
          <h2>What documents might be used to support an appeal?</h2>
          <p className="content-paragraph">
            The types of supporting documents may vary depending upon the circumstances of the appeal, but typically include: invoices, proof of payment, books of account, financial statements and similar.
          </p>
          <p className="content-paragraph">
            It is important to note any documents used to support appeals following the conclusion of audits must have also been provided at the time of the audit.
          </p>
        </section>

        {/* Risks Section */}
        <section className="content-section">
          <h2>Can appeals make assessments worse for the taxpayer?</h2>
          <p className="content-paragraph">
            There is no penalty or fine for making unsuccessful appeals. However, appeals could potentially lead to further assessment of the case and the uncovering of new information leading to additional penalties or fines.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Appeals;
