import { TrendingDown } from 'lucide-react';

const DebtManagement = () => {
  return (
    <div className="page-container">
      <div className="professional-header">
        <div className="professional-header-content">
          <div className="professional-title-container">
            <div className="professional-title-icon">
              <TrendingDown size={24} />
            </div>
            <div className="professional-title-text">
              <h1 className="professional-main-title">Debt Management</h1>
              <div className="professional-title-divider"></div>
            </div>
          </div>
        </div>
      </div>

      <div className="page-content">
        {/* What is a Tax Debt Section */}
        <section className="content-section">
          <h2>What is a tax debt?</h2>
          <p className="content-paragraph">
            A tax debt is the amount of money a taxpayer (individual or business) owes to a tax authority due to:
          </p>
          <ul className="content-list">
            <li>Unpaid taxes from previous periods</li>
            <li>Underreported income or incorrect tax filings</li>
            <li>Penalties and interest for late payments or non-compliance.</li>
          </ul>
        </section>

        {/* When Tax Becomes Debt Section */}
        <section className="content-section">
          <h2>When a tax becomes a debt?</h2>
          <p className="content-paragraph">
            Tax debt arises when the tax due is not paid in full by the deadline upon reception of notice of assessment automatically generated by the system or after audit. It remains a liability until it is settled through payment, offset, or other arrangements like installment plans or waivers.
          </p>
        </section>

        {/* Installment Payment Section */}
        <section className="content-section">
          <h2>What is the procedure for paying taxes in instalments?</h2>
          <p className="content-paragraph">
            Taxpayers who are unable to pay tax arrears or assessment notices at once may apply to pay in instalments.
          </p>
          <p className="content-paragraph">
            In order to apply to pay in instalments, the taxpayer must pay at least 10% of the tax due before applying. The payment plan must show an intention to pay the full amount within a maximum period of 12 months. However, the Commissioner General may extend this period by another period not exceeding 24 months if the taxpayer has justified reasons. The taxpayer should also offer, and provide evidence of, a guarantee, that could be seized by RRA in the event of non-compliance with the approved payment plan.
          </p>
          <p className="content-paragraph">
            Taxpayers must then write a letter addressed to the Commissioner General of RRA. This letter should:
          </p>
          <ul className="content-list">
            <li>Identify the taxpayer's name and TIN</li>
            <li>Identify the tax period and tax type(s) concerned</li>
            <li>State the amount of tax due</li>
            <li>State the reason(s) for not being able to pay the whole amount of tax due at once</li>
            <li>Contain their instalment payment plan</li>
            <li>Contain proof of payment of at least 10% of the amount due</li>
            <li>Contain evidence of a guarantee</li>
            <li>Be signed by the taxpayer or legal representative</li>
          </ul>
          <p className="content-paragraph">
            If the instalment payment plan is approved, the taxpayer and RRA will sign an official agreement detailing the instalment payment plan. Any failure to comply with the payment plan results in the immediate enforcement of the total amount due, and may result in the seizure of the guarantee.
          </p>
        </section>

        {/* Waiver Procedure Section */}
        <section className="content-section">
          <h2>What is the procedure for waivers of any taxes due?</h2>
          <p className="content-paragraph">
            In special circumstances, taxpayers may also request for taxes or penalties to be waived or dropped. Although these requests must be made to RRA, the decision to grant any waivers waive any fines or interest due is the responsibility of the Ministry of Finance and Economic Planning (MINECOFIN). However, waiving the principal tax is done by the Cabinet upon request of MINECOFIN.
          </p>
          <p className="content-paragraph">
            In order to request a waiver, taxpayers must write a letter addressed to the Commissioner General of RRA. This letter should:
          </p>
          <ul className="content-list">
            <li>Identify the taxpayer's name and TIN.</li>
            <li>Identify the tax period and tax type(s) concerned.</li>
            <li>State the amount of tax due.</li>
            <li>State the reason(s) for the waiver request.</li>
            <li>Contain any supporting evidence as required.</li>
            <li>Be signed by the taxpayer or legal representative.</li>
          </ul>
          <p className="content-paragraph">
            RRA will acknowledge receipt of the letter, but the timeline, result and communication of the decision is the responsibility of MINECOFIN.
          </p>
        </section>

        {/* Enforcement Procedure Section */}
        <section className="content-section">
          <h2>What is the procedure for the enforcement of arrears?</h2>
          <p className="content-paragraph">
            There are many enforcement actions legally available to RRA for the collection of unpaid tax arrears. The typical process is in three steps. Firstly, the taxpayer receives a warning letter from RRA, requesting they visit RRA offices to discuss the arrears situation and repayment options.
          </p>
          <p className="content-paragraph">
            If there is no response within fifteen days, RRA may begin 'garnishment'. This means that RRA may work with third parties, such as banks, to freeze the taxpayers' accounts. Finally, RRA may begin search and seizure of movable and immovable assets. This can be sold at auction. A publication of auction must be made (in a public newspaper) at least 15 days before the auction is conducted.
          </p>
        </section>
      </div>
    </div>
  );
};

export default DebtManagement;
